generatorName: motoko
outputDir: samples/client/nested-arrays/motoko-test/generated
inputSpec: samples/client/nested-arrays/motoko-test/specs/nested-arrays.json
templateDir: modules/openapi-generator/src/main/resources/motoko
artifactId: nested-arrays-client
artifactVersion: 1.0.0
additionalProperties:
  hideGenerationTimestamp: "true"
  useDfx: false
