generatorName: motoko
outputDir: samples/client/type-coverage/motoko-test/generated
inputSpec: samples/client/type-coverage/motoko-test/specs/type-coverage.json
templateDir: modules/openapi-generator/src/main/resources/motoko
artifactId: type-coverage-client
artifactVersion: 1.0.0
additionalProperties:
  hideGenerationTimestamp: "true"
  useDfx: false
