generatorName: motoko
outputDir: samples/client/spotify/motoko/generated
inputSpec: samples/client/spotify/motoko/specs/spotify-openapi.yml
templateDir: modules/openapi-generator/src/main/resources/motoko
artifactId: spotify-client
artifactVersion: 1.0.0
additionalProperties:
  hideGenerationTimestamp: "true"
  useDfx: false
